image:
  file: .gitpod.Dockerfile
ports:
- port: 9323
- port: 8888
tasks:
  - name: Install JupyterLab Node.js testing dependencies
    init: |
      cd testing/jupyterlab
      yarn install
      npx playwright install chromium
    command: yarn test
