name: ci

on:
  # TODO: these should be tightened up
  push:
    branches: "*"
  pull_request:
    branches: "*"

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@master
        with:
          environment-file: .binder/environment.yml
          miniforge-variant: Mambaforge
          use-mamba: true
      - run: |
          set -eux
          bash postBuild
      - run: |
          set -eux
          doit report
      - uses: actions/upload-artifact@v2
        with:
          name: accessibility ${{ github.run_number }}
          path: |
            reports
            logs
        if: always()
