name: ci

on:
  # TODO: these should be tightened up
  # push:
  #   branches: "*"
  pull_request:
    branches: "*"

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2

      - name: Set Up environment like binder
        uses: conda-incubator/setup-miniconda@master
        with:
          environment-file: .binder/environment.yml
          miniforge-variant: Mambaforge
          use-mamba: true

      - name: Run binder postBuild
        run: |
          set -eux
          bash .binder/postBuild

      - name: Upload Logs
        uses: actions/upload-artifact@v2
        with:
          name: accessibility logs ${{ github.run_number }}
          path: |
            logs
        if: always()

      - name: Generate reports
        run: |
          set -eux
          doit report

      - name: Upload reports
        uses: actions/upload-artifact@v2
        with:
          name: accessibility ${{ github.run_number }}
          path: |
            reports
        if: always()
