name: jupyter book documentation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
        name: Fetch all history for all tags and branches
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: python -m pip install nox
      - name: Build the docs with nox
        run: nox -s docs
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: _build/html
          target-folder: ${{ github.ref }}