name: a11y tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
        name: Fetch all history for all tags and branches
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
      - name: Install dependencies
        run: |
          pwd
          python -m pip install -e .
          python -m jupyter_accessibility -i retrolab -- list
          python -m jupyter_accessibility -i retrolab -- env
          python -m jupyter_accessibility -i retrolab -- setup
          python -m jupyter_accessibility -i retrolab -- test_setup
          python -m jupyter_accessibility -i retrolab -- test

  - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: a11y-test-results
          path: |
            jupyter-ally-build/jupyter-axe/test-results/*.json
            jupyter-ally-build/jupyter-axe/test-results/**/*.json

